name: Comment pull requests
on:
  issues:
    types:
      - closed
  pull_request:
    types:
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Attach label to issues
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["issue", "fix"]
            })
  comment_on_close:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment on closed issue
        if: github.event_name == 'issues' && github.event.action == 'closed'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            The issue is now resolved.
  comment_on_pull_request:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment on pull request
        if: github.event_name == 'pull_request' && github.event.number == 1
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.issue_url | replace('/pulls/', '/issues/') }}
          body: |
            Congratulations on opening your first pull request!.
